### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Waller1337** [Luc4sguilherme/Steam-levelup-BOT#81]
I followed this `https://github.com/Luc4sguilherme/Steam-levelup-BOT/blob/master/TUTORIAL.md` but there is such an error during start-up

nohup: ignoring input
/root/Steam-levelup-BOT/src/Utils/index.js:506
    const section = message[indexSection(`Suppliers Section.`)]?.replace(
                                                                ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:1070:16)
    at Module._compile (internal/modules/cjs/loader.js:1120:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/root/Steam-levelup-BOT/src/index.js:9:15)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)

**Comment by Luc4sguilherme** [comment]
@Waller1337 What version of node.js are you using?

**Comment by Waller1337** [comment]
v12.16.2

**Comment by Luc4sguilherme** [comment]
Upgrade to version 14.17.4 LTS

**Comment by Waller1337** [comment]
now its working, thank you
